<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZXl47mV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZXl47mV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZXl47mV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZXl47mV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZXl47mV\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZXl47mV',
    'container.build_id' => '68095ae5',
    'container.build_time' => 1578163588,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZXl47mV');
